version: "3.8"
services:
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      POSTGRES-USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: events_db
    ports:
      - '5432:5432'