server:
  port: 8050
spring:
  application:
    name: event-service
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/events_db
    username: postgres
    password: password
  flyway:
    url: jdbc:postgresql://localhost:5432/events_db
    user: postgres
    password: password

eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
