eureka:
  client:
    register-with-eureka: false

server:
  port: 8080
spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: events
          uri: http://localhost:8050
          predicates:
            - Path=/api/v1/eventos/**
        - id: tickets
          uri: http://localhost:8051
          predicates:
            - Path=/api/v1/tickets/**
        - id: order
          uri: http://localhost:8052
          predicates:
            - Path=/order/**
        - id: inventary
          uri: http://localhost:8053
          predicates:
            - Path=/inventory/**
        - id: payment
          uri: http://localhost:8054
          predicates:
            - Path=/payment/**
        - id: orchestrator
          uri: http://localhost:8055
          predicates:
            - Path=/**
---
spring:
  application:
    name: gateway-service
  config:
    import: optional:configserver:http://localhost:8888