server:
  port: 8052
spring:
  application:
    name: order-service
  data:
    mongodb:
      uri: mongodb://localhost:28017/orders_db
  cloud:
    function:
      definition: supplier;consumer
    stream:
      bindings:
        supplier-out-0:
          destination: order-created
        consumer-in-0:
          destination: order-updated
eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

---
spring:
  application:
    name: order-service
  config:
    import: optional:configserver:http://localhost:8888